# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui',
# licensing of 'gui.ui' applies.
#
# Created: Sat Apr  4 14:57:07 2020
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1124, 714)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.img = QtWidgets.QLabel(Dialog)
        self.img.setGeometry(QtCore.QRect(300, 80, 800, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img.sizePolicy().hasHeightForWidth())
        self.img.setSizePolicy(sizePolicy)
        self.img.setFrameShape(QtWidgets.QFrame.Box)
        self.img.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.img.setText("")
        self.img.setAlignment(QtCore.Qt.AlignCenter)
        self.img.setObjectName("img")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 251, 421))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 231, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.temp_min = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.temp_min.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.temp_min.setFont(font)
        self.temp_min.setProperty("value", 35.0)
        self.temp_min.setObjectName("temp_min")
        self.horizontalLayout.addWidget(self.temp_min)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.temp_max = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.temp_max.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.temp_max.setFont(font)
        self.temp_max.setProperty("value", 45.0)
        self.temp_max.setObjectName("temp_max")
        self.horizontalLayout_2.addWidget(self.temp_max)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 85, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.emisividad = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.emisividad.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.emisividad.setFont(font)
        self.emisividad.setMaximum(1.0)
        self.emisividad.setSingleStep(0.01)
        self.emisividad.setProperty("value", 0.97)
        self.emisividad.setObjectName("emisividad")
        self.horizontalLayout_3.addWidget(self.emisividad)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.umbral_fiebre = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.umbral_fiebre.setEnabled(False)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.umbral_fiebre.setFont(font)
        self.umbral_fiebre.setProperty("value", 37.7)
        self.umbral_fiebre.setObjectName("umbral_fiebre")
        self.horizontalLayout_4.addWidget(self.umbral_fiebre)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.unlock = QtWidgets.QPushButton(Dialog)
        self.unlock.setGeometry(QtCore.QRect(40, 500, 91, 27))
        self.unlock.setObjectName("unlock")
        self.lock = QtWidgets.QPushButton(Dialog)
        self.lock.setEnabled(False)
        self.lock.setGeometry(QtCore.QRect(150, 500, 88, 27))
        self.lock.setObjectName("lock")

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.unlock, QtCore.SIGNAL("clicked()"), Dialog.unlock_conf)
        QtCore.QObject.connect(self.lock, QtCore.SIGNAL("clicked()"), Dialog.lock_conf)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Medición de temperatura corporal IR - CITEDEF - COVID-19", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Configuración", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Calibracion cuerpo negro", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Temp. Mínima:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Temp. Máxima:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Medición y detección", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Emisividad de la piel:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Umbral de fiebre:", None, -1))
        self.unlock.setText(QtWidgets.QApplication.translate("Dialog", "Desbloquea", None, -1))
        self.lock.setText(QtWidgets.QApplication.translate("Dialog", "Bloquea", None, -1))

